services:
  - type: web
    name: binomena-node
    env: go
    region: frankfurt
    plan: starter
    buildCommand: go mod download && go build -o app
    startCommand: ./app
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: binomena-db
          property: connectionString
      - key: DB_PASSWORD
        fromDatabase:
          name: binomena-db
          property: password
      - key: PORT
        value: 10000
      - key: NODE_ID
        value: genesis-node
      - key: DEBUG
        value: false
      - key: GIN_MODE
        value: release
    autoDeploy: true

databases:
  - name: binomena-db
    databaseName: binomena_bq
    user: binomuser
    region: frankfurt
    plan: starter