services:
  - type: web
    name: binomena-node
    env: go
    buildCommand: go build -o binomena
    startCommand: ./start.sh
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ID
        value: genesis-node
    disk:
      name: blockchain-data
      mountPath: /opt/render/project/src/data
      sizeGB: 10
    autoDeploy: true
