services:
  - type: web
    name: binomena-node
    env: go
    region: frankfurt
    plan: starter
    buildCommand: go mod download && go build -o app
    startCommand: ./app
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: postgresql://binomuser:EILWycLJTjfxQgFtUWpTGISbSycB3Ubn@dpg-d0n585mmcj7s7397fpsg-a/binomena_bq
      - key: DB_PASSWORD
        value: EILWycLJTjfxQgFtUWpTGISbSycB3Ubn
      - key: PORT
        value: 10000
      - key: NODE_ID
        value: genesis-node
      - key: DEBUG
        value: false
    autoDeploy: true